const PRODUCTS = [
  {
    id: 1,
    name: "Kaos Oversized Essential",
    category: "pakaian",
    price: 189000,
    originalPrice: 279000,
    discount: 32,
    rating: 4.8,
    reviewCount: 324,
    badge: "sale",
    emoji: "👕",
    colors: ["#1A1A2E","#F8F4EF","#E63946","#06D6A0"],
    sizes: ["S","M","L","XL","XXL"],
    description: "Kaos oversized premium dari bahan cotton combed 30s. Nyaman dipakai seharian, cocok untuk berbagai aktivitas.",
    featured: true,
    stock: 85
  },
  {
    id: 2,
    name: "Celana Cargo Street",
    category: "pakaian",
    price: 349000,
    originalPrice: 349000,
    discount: 0,
    rating: 4.9,
    reviewCount: 187,
    badge: "new",
    emoji: "👖",
    colors: ["#3D3D3D","#8B7355","#1A1A2E"],
    sizes: ["28","30","32","34","36"],
    description: "Celana cargo dengan banyak kantong fungsional. Material twill tebal, anti lusuh.",
    featured: true,
    stock: 42
  },
  {
    id: 3,
    name: "Sneakers Urban Runner",
    category: "sepatu",
    price: 549000,
    originalPrice: 799000,
    discount: 31,
    rating: 4.7,
    reviewCount: 512,
    badge: "sale",
    emoji: "👟",
    colors: ["#FFFFFF","#1A1A2E","#E63946"],
    sizes: ["38","39","40","41","42","43"],
    description: "Sneakers ringan dengan sol chunky. Outsole karet anti-slip, cocok untuk jalan maupun olahraga ringan.",
    featured: true,
    stock: 28
  },
  {
    id: 4,
    name: "Tote Bag Canvas Premium",
    category: "tas",
    price: 229000,
    originalPrice: 229000,
    discount: 0,
    rating: 4.6,
    reviewCount: 93,
    badge: "new",
    emoji: "👜",
    colors: ["#F8F4EF","#1A1A2E","#8B7355"],
    sizes: ["One Size"],
    description: "Tote bag canvas 12oz, kuat dan spacious. Ada zipper pocket di dalam, bisa lipat jadi kecil.",
    featured: true,
    stock: 67
  },
  {
    id: 5,
    name: "Kemeja Flannel Weekend",
    category: "pakaian",
    price: 299000,
    originalPrice: 399000,
    discount: 25,
    rating: 4.8,
    reviewCount: 241,
    badge: "sale",
    emoji: "🧥",
    colors: ["#8B2635","#1A3A2E","#2E3A8B"],
    sizes: ["S","M","L","XL"],
    description: "Kemeja flannel motif kotak klasik. Bisa dipakai sebagai outer atau shirt biasa.",
    featured: true,
    stock: 38
  },
  {
    id: 6,
    name: "Cap Bordir Logo",
    category: "aksesoris",
    price: 149000,
    originalPrice: 149000,
    discount: 0,
    rating: 4.5,
    reviewCount: 156,
    badge: "hit",
    emoji: "🧢",
    colors: ["#1A1A2E","#F8F4EF","#E63946","#06D6A0"],
    sizes: ["One Size"],
    description: "Topi cap 6-panel dengan bordir logo UrbanDrop. Adjustable strap, cocok untuk semua kepala.",
    featured: false,
    stock: 124
  },
  {
    id: 7,
    name: "Celana Jogger Comfort",
    category: "pakaian",
    price: 269000,
    originalPrice: 369000,
    discount: 27,
    rating: 4.7,
    reviewCount: 298,
    badge: "sale",
    emoji: "🩳",
    colors: ["#3D3D3D","#F8F4EF","#8B7355"],
    sizes: ["S","M","L","XL","XXL"],
    description: "Celana jogger dengan bahan french terry. Pinggang elastis dengan tali, sangat nyaman untuk WFH atau jogging.",
    featured: false,
    stock: 72
  },
  {
    id: 8,
    name: "Tas Selempang Mini",
    category: "tas",
    price: 189000,
    originalPrice: 189000,
    discount: 0,
    rating: 4.6,
    reviewCount: 88,
    badge: "new",
    emoji: "👝",
    colors: ["#1A1A2E","#8B2635","#8B7355"],
    sizes: ["One Size"],
    description: "Tas selempang mini PU leather premium. Cukup untuk HP, kartu, dan dompet. Tali adjustable.",
    featured: false,
    stock: 55
  },
  {
    id: 9,
    name: "Sandal Slide Bertekstur",
    category: "sepatu",
    price: 199000,
    originalPrice: 259000,
    discount: 23,
    rating: 4.5,
    reviewCount: 167,
    badge: "sale",
    emoji: "🩴",
    colors: ["#1A1A2E","#F8F4EF","#8B7355"],
    sizes: ["37","38","39","40","41","42","43"],
    description: "Sandal slide dengan footbed bertekstur anti-slip. Sol tebal 4cm, nyaman untuk pemakaian harian.",
    featured: false,
    stock: 93
  },
  {
    id: 10,
    name: "Gelang Anyam Boho",
    category: "aksesoris",
    price: 89000,
    originalPrice: 89000,
    discount: 0,
    rating: 4.4,
    reviewCount: 74,
    badge: null,
    emoji: "📿",
    colors: ["#8B7355","#E63946","#1A3A2E"],
    sizes: ["One Size"],
    description: "Gelang anyam tangan dengan manik-manik. Dibuat oleh pengrajin lokal, setiap gelang unik.",
    featured: false,
    stock: 210
  },
  {
    id: 11,
    name: "Hoodie Colorblock",
    category: "pakaian",
    price: 399000,
    originalPrice: 499000,
    discount: 20,
    rating: 4.9,
    reviewCount: 401,
    badge: "sale",
    emoji: "🧣",
    colors: ["#1A1A2E","#E63946","#06D6A0"],
    sizes: ["S","M","L","XL","XXL"],
    description: "Hoodie colorblock dengan desain asimetris. Bahan fleece premium, hangat dan stylish.",
    featured: false,
    stock: 31
  },
  {
    id: 12,
    name: "Kacamata Wayfarer Vintage",
    category: "aksesoris",
    price: 169000,
    originalPrice: 169000,
    discount: 0,
    rating: 4.6,
    reviewCount: 119,
    badge: "hit",
    emoji: "🕶️",
    colors: ["#1A1A2E","#8B7355","#3D3D3D"],
    sizes: ["One Size"],
    description: "Kacamata wayfarer retro dengan lensa UV400. Frame acetate ringan, cocok untuk berbagai bentuk wajah.",
    featured: false,
    stock: 78
  }
];

const TESTIMONIALS = [
  {
    name: "Aulia Rahma",
    initials: "AR",
    avatarColor: "#FFD166",
    textColor: "#1A1A2E",
    product: "Kaos Oversized Essential",
    rating: 5,
    text: "Udah lama nyari kaos oversized yang beneran bagus, ini cocok banget! Bahan adem, jahitan rapi, dan ukurannya pas. Beli lagi ah!"
  },
  {
    name: "Dimas Pratama",
    initials: "DP",
    avatarColor: "#1A1A2E",
    textColor: "#FFFFFF",
    product: "Sneakers Urban Runner",
    rating: 5,
    text: "Sepatu ini beneran nyaman dipakai seharian. Udah dipake jalan-jalan ke mall 8 jam, kaki tetep fine. Worth every penny!"
  },
  {
    name: "Sinta Maharani",
    initials: "SM",
    avatarColor: "#06D6A0",
    textColor: "#1A1A2E",
    product: "Tote Bag Canvas Premium",
    rating: 4,
    text: "Tasnya besar dan kuat! Muat laptop + buku + minum. Harga segini untuk kualitas ini? Kaget sendiri. Recommended banget!"
  },
  {
    name: "Rizky Kurniawan",
    initials: "RK",
    avatarColor: "#E63946",
    textColor: "#FFFFFF",
    product: "Hoodie Colorblock",
    rating: 5,
    text: "Hoodie paling keren yang pernah aku beli. Desainnya unik, nggak pasaran. Tiap keluar pakai ini pasti ada yang nanya beli dimana."
  },
  {
    name: "Mega Lestari",
    initials: "ML",
    avatarColor: "#8B7355",
    textColor: "#FFFFFF",
    product: "Celana Cargo Street",
    rating: 5,
    text: "Celana cargo impian akhirnya ketemu! Kantongnya banyak dan dalam, bahan tebal tapi ringan. Pengiriman juga super cepat!"
  },
  {
    name: "Bayu Aditya",
    initials: "BA",
    avatarColor: "#F8F4EF",
    textColor: "#1A1A2E",
    product: "Cap Bordir Logo",
    rating: 4,
    text: "Topinya bagus, bordirannya rapi dan nggak copot meski udah sering dicuci. Size-nya pas untuk kepala besar sekalipun."
  }
];

// Ekspor global
window.PRODUCTS = PRODUCTS;
window.TESTIMONIALS = TESTIMONIALS;
